# Generated by Django 4.2.4 on 2023-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodemain', '0002_qrcode_scan_count_qrcode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
