# Generated by Django 4.2.4 on 2023-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodemain', '0003_alter_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
